version: '3'

services:
  postgresql:
    build:
      context: .
      dockerfile: ./docker/postgresql/Dockerfile
    ports:
      - 5432:5432
  application:
    build:
      context: .
      dockerfile: ./docker/home-work/Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - postgresql
