logging:
  level:
    ROOT: INFO

spring:
  banner:
    location: classpath:banner.txt

  h2:
    console:
      enabled: true
      path: "/h2-console"

  datasource:
    driver-class-name: org.h2.Driver
    initialization-mode: ALWAYS
    url: "jdbc:h2:mem:db;DB_CLOSE_DELAY=-1"
    # url: "jdbc:h2:tcp://localhost/~/db/h2/books"
    username: sa
    password: sa

  data:
    mongodb:
      host: localhost
      port: 27017
      database: books

  jpa:
    generate-ddl: true
    show-sql: false
    hibernate:
      ddl-auto: create
      hbm2ddl:
        auto: create

  batch:
    job:
      enabled: false

application:
  locale: "ru_RU"
