logging:
  level:
    ROOT: INFO

spring:
  banner:
    location: classpath:banner.txt

  datasource:
<<<<<<< HEAD
    driver-class-name: org.h2.Driver
    initialization-mode: ALWAYS
    url: "jdbc:h2:mem:db;DB_CLOSE_DELAY=-1"
    username: sa
    password: sa

  h2:
    console:
      enabled: true

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create

locale: "ru_RU"
=======
    platform: postgres
    url: jdbc:postgresql://postgresql:5432/db
    username: dbuser
    password: password

  jpa:
    generate-ddl: true
    show-sql: false
    hibernate:
      ddl-auto: update
      hbm2ddl:
        auto: create

application:
  rememberKey: "RememberMeApplicationKey"
  locale: "ru_RU"
  strength: 4
>>>>>>> 3c01fc04fe97660798e73fdae8736623943ae16e
