apiVersion: v1
kind: Template
labels:
  demo: rhel7-jre8-hello-demo
  template: rhel7-jre8-hello-demo
metadata:
  annotations:
    description: A simple jre 8 container using starter beta from microprofile.io
    iconClass: icon-java
    tags: microservice,microprofile,thorntail
  name: rhel7-jre8-hello-demo

objects:
- apiVersion: v1
  groupNames: null
  kind: RoleBinding
  metadata:
    name: default_edit
  roleRef:
    name: view
  subjects:
  - kind: ServiceAccount
    name: default

- apiVersion: v1
  kind: ImageStream
  metadata:
    name: rhel7-jre8-hello-demo
  spec:
    dockerImageRepository: vs1756.imb.ru:5000/am24681/hello

- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: rhel7-jre8-hello-demo
  spec:
    template:
      metadata:
        labels:
          name: rhel7-jre8-hello-demo
      spec:
        containers:
          - image: vs1756.imb.ru:5000/am24681/hello:latest
            name: rhel7-jre8-hello-demo
            ports:
              - containerPort: 8080
                protocol: TCP
    replicas: 1
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - rhel7-jre8-hello-demo
        from:
          kind: ImageStreamTag
          name: rhel7-jre8-hello-demo:latest
      type: ImageChange

- apiVersion: v1
  kind: Service
  metadata:
    name: rhel7-jre8-hello-demo
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      deploymentconfig: rhel7-jre8-hello-demo

- apiVersion: v1
  kind: Route
  metadata:
    name: rhel7-jre8-hello-demo
  spec:
    port:
      targetPort: 8080-tcp
    to:
      kind: Service
      name: rhel7-jre8-hello-demo
      weight: 100
