spring:
  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:testdb

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none

  messages:
    basename: i18n/bundle

application:
  key: "AnyAppKey"
  locale: ru-RU