DROP TABLE IF EXISTS books_genres;
DROP TABLE IF EXISTS  books_authors;
DROP TABLE IF EXISTS  books_comments;
DROP TABLE IF EXISTS  books;
DROP TABLE IF EXISTS  genres;
DROP TABLE IF EXISTS  authors;
DROP TABLE IF EXISTS  users;

CREATE TABLE authors(id BIGINT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(255));
CREATE TABLE genres(id BIGINT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(255));
CREATE TABLE books(id BIGINT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(255), description VARCHAR(8000), pub_year INT);
CREATE TABLE books_authors(book_id BIGINT, author_id BIGINT, FOREIGN KEY(book_id) REFERENCES books(id) ON DELETE CASCADE, FOREIGN KEY(author_id) REFERENCES authors(id) ON DELETE CASCADE);
CREATE TABLE books_genres(book_id BIGINT, genre_id BIGINT, FOREIGN KEY(book_id) REFERENCES books(id) ON DELETE CASCADE, FOREIGN KEY(genre_id) REFERENCES genres(id) ON DELETE CASCADE);
CREATE TABLE books_comments(id BIGINT AUTO_INCREMENT PRIMARY KEY, book_id BIGINT, commenting_time DATETIME DEFAULT CURRENT_TIMESTAMP, author VARCHAR(255), comment VARCHAR(255), FOREIGN KEY(book_id) REFERENCES books(id) ON DELETE CASCADE);
CREATE TABLE users(id BIGINT AUTO_INCREMENT PRIMARY KEY, login VARCHAR(255), password VARCHAR(255));
